src/bundle/Resources/views/RichText/content_fields.html.twig
| **JIRA issue**                          | [IBX-538](https://issues.ibexa.co/browse/IBX-538)
| **Requires**                            | ibexa/core#13
| **Type**                                   | feature
| **BC breaks**                          | yes
ibexa/core#13 updates `ibexa/core` Bundle names with proper Ibexa prefix instead of EzPublish. This PR aligns Twig namespace references with the bundle name change.
=> IBX-538: Replaced EzPublishCore Twig namespace references with IbexaCore

src/bundle/Resources/encore/ez.webpack.custom.config.js, src/bundle/Resources/public/js/CKEditor/anchor/anchor-ui.js, src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-command.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-editing.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-ui.js, src/bundle/Resources/public/js/CKEditor/custom-styles/inline/custom-style-inline-ui.js, src/bundle/Resources/public/js/CKEditor/custom-styles/inline/custom-styles-inline.js, src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-editing.js, src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js, src/bundle/Resources/public/js/CKEditor/custom-tags/custom-tags.js, src/bundle/Resources/public/js/CKEditor/custom-tags/ui/custom-tag-attributes-view.js, src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-editing.js, src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-ui.js, src/bundle/Resources/public/js/CKEditor/embed/content/embed-editing.js, src/bundle/Resources/public/js/CKEditor/embed/content/embed-ui.js, src/bundle/Resources/public/js/CKEditor/embed/embed-base-ui.js, src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js, src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-ui.js, src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-variations-ui.js, src/bundle/Resources/public/js/CKEditor/formatted/formatted-ui.js, src/bundle/Resources/public/js/CKEditor/link/link-ui.js, src/bundle/Resources/public/js/CKEditor/link/ui/link-form-view.js, src/bundle/Resources/public/js/CKEditor/move/move-down-ui.js, src/bundle/Resources/public/js/CKEditor/move/move-up-ui.js, src/bundle/Resources/public/js/CKEditor/remove-element/remove-element-ui.js, src/bundle/Resources/public/js/CKEditor/services/content-service.js, src/bundle/Resources/public/scss/_general.scss, tests/lib/RichText/Converter/AggregateTest.php
| **JIRA issue**                          | [IBX-1689](https://issues.ibexa.co/browse/IBX-1689)
| **Type**                                   | improvement
| **BC breaks**                          | yes
Changed all eZ/ez- frontend classes/variables to ibexa
Related PRs:
- https://github.com/ibexa/admin-ui/pull/111
- https://github.com/ibexa/calendar/pull/15
- https://github.com/ibexa/commerce-admin-ui/pull/23
- https://github.com/ibexa/commerce-base-design/pull/11
- https://github.com/ibexa/commerce-checkout/pull/10
- https://github.com/ibexa/commerce-fieldtypes/pull/11
- https://github.com/ibexa/commerce-page-builder/pull/11
- …
=> IBX-1689: Change all ez- classes/IDs and eZ variables in frontend part

src/bundle/DependencyInjection/Compiler/RichTextHtml5ConverterPass.php, src/bundle/DependencyInjection/IbexaFieldTypeRichTextExtension.php, src/bundle/Resources/config/configuration.yaml, src/bundle/Resources/config/fieldtype_services.yaml, src/bundle/Resources/config/form.yaml, src/bundle/Resources/config/settings/fieldtype_external_storages.yaml, src/bundle/Resources/config/settings/fieldtype_services.yaml, src/bundle/Resources/config/settings/fieldtypes.yaml, src/bundle/Resources/config/settings/indexable_fieldtypes.yaml, src/bundle/Resources/config/settings/storage_engines/legacy/field_value_converters.yaml, src/bundle/Resources/config/ui/mappers.yaml, tests/bundle/DependencyInjection/Compiler/RichTextHtml5ConverterPassTest.php
| **JIRA issue**                          | [IBX-1694](https://issues.ibexa.co/browse/IBX-1694)
| **Type**                                   | feature
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#12
In this Pull Request we rename Ibexa's dependency injection container service tags according to the map provided by ibexa/compatibility-layer#12 as a part of the rebranding process. Backward compatibility for old service tags is provided by ibexa/compatibility-layer#12.
=> IBX-1694: Rebranded dependency injection container service tags

src/bundle/Resources/config/prepend/ezpublish.yaml
JIRA: https://issues.ibexa.co/browse/IBX-2028
The problem is not with inability to add custom tags. Default custom tags (social media buttons) have been accidentally removed here: https://github.com/ibexa/fieldtype-richtext/commit/bac7c8e22f6bd5cb2e1760bc21ca2190b26a8953#diff-436dce8a20ae62140f2de6ec8dbec1533068c7f0796de0d61eb3aab6f2648589L14
=> IBX-2028: Restored default custom tags to configuration

src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js
| **JIRA issue**                          | [IBX-1832](https://issues.ibexa.co/browse/IBX-1832)
| **Type**                                   | bug
| **BC breaks**                          | yes
Embed configuration keys cannot contain whitespaces, as there's no way to determine if given configuration key should have them trimmed or not - it's too generic at that point
```xml
<span data-ezelement="ezvalue" data-ezvalue-key="size">medium</span>
```
is the proper formatting the payload should have.
=> IBX-1832: Removed whitespaces from image embed configuration payload

composer.json, src/bundle/DependencyInjection/IbexaFieldTypeRichTextExtension.php, src/bundle/Resources/encore/ez.webpack.custom.config.js, tests/bundle/DependencyInjection/Configuration/Parser/FieldType/RichTextTest.php, tests/bundle/DependencyInjection/ContainerParameterLoader.php, tests/bundle/DependencyInjection/ContainerParameterLoaderTrait.php, tests/bundle/DependencyInjection/IbexaFieldTypeRichTextExtensionTest.php
| **JIRA issue**                          | [IBX-2961](https://issues.ibexa.co/browse/IBX-2961)
| **Requires**                            | ibexa/core#120
| **Type**                                   | bug
| **Target Ibexa version** | `v4.1`+
| **BC breaks**                          | no
| **Tests**                            | <ul><li>[Passing CI build with ibexa/core dependency](https://github.com/ibexa/fieldtype-richtext/actions/runs/2494846208)</li><li>ibexa/commerce#102</li></ul>
Related changes:
- ibexa/admin-ui#471
See also ibexa/admin-ui#471 for Doc.
We need to extend this part of the documentation: https://doc.ibexa.co/en/latest/extending/extending_online_editor/#ad …
=> IBX-2961: Fixed extensibility point for adding plugins in CKEditor

src/bundle/Resources/public/js/CKEditor/custom-tags/inline-custom-tag/inline-custom-tag-editing.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-2555
| **New feature**    | yno
| **Target version** | 4.1
**TODO**:
=> IBX-2555: Fixed double content in inline custom tags

src/bundle/DependencyInjection/Configuration.php, src/lib/Configuration/UI/Mapper/CustomTag.php
| **JIRA issue**     | -
| **New feature**    | -
| **Target version** | `4.2.0`
| **BC breaks**      | -
Fixed not working translations extraction due to 
```
Can only extract the translation id from a scalar string, but got "PhpParser\Node\Expr\Variable". Please refactor your code to make it extractable, or add the doc comment /** @Ignore */ to this code element (in /home/awojs/ibexa/ibexa-4.2-for-trans-extra/vendor/ibexa/fieldtype-richtext/src/bundle/DependencyInjection/../../../src/lib/Configuration/UI/Mapper/CustomTag.php on line 193).
```
error.
**TODO**:
=> Fixed a translations extraction

.github/workflows/ci.yaml
| **JIRA issue**     | n/a
| **Bug/Improvement**| CI improvement
| **Target version** | 4.2, 4.3 and future versions
I've removed the hardcoded version from CI and switched to relying on branch-alias - it gets updated with every stable branch, so we won't have to change this additional place with every release.
**TODO**:
=> [CI] Removed hardcoded Solr version and switched to one relying on branch-alias

src/bundle/Resources/public/scss/_general.scss, src/bundle/Resources/public/scss/variables/colors.scss
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-3973
| **Target version** | `main`
=> IBX-3973: Nontranslatable and disabled fields are not greyed out in content editing UI

src/bundle/Resources/config/fieldtype_services.yaml, src/lib/RichText/Converter/Link.php, tests/lib/RichText/Converter/LinkTest.php
| **JIRA issue**     | N/A
| **Target version** | `main`
Using `UrlAliasRouter` directly prevents from using the chain routing mechanism and implementing a custom router in a clean way.
**TODO**:
=> Use Symfony's router instead of UrlAlias router

src/bundle/Resources/richtext/schemas/docbook/ezpublish.rng, src/bundle/Resources/richtext/stylesheets/docbook/xhtml5/edit/core.xsl, src/bundle/Resources/richtext/stylesheets/docbook/xhtml5/output/core.xsl, src/bundle/Resources/richtext/stylesheets/xhtml5/edit/docbook.xsl, tests/lib/RichText/Converter/Xslt/_fixtures/docbook/036-itemizedListFormatted.xml, tests/lib/RichText/Converter/Xslt/_fixtures/docbook/037-orderedListFormatted.xml, tests/lib/RichText/Converter/Xslt/_fixtures/xhtml5/edit/036-itemizedListFormatted.xml, tests/lib/RichText/Converter/Xslt/_fixtures/xhtml5/edit/037-orderedListFormatted.xml, tests/lib/RichText/Converter/Xslt/_fixtures/xhtml5/output/036-itemizedListFormatted.xml, tests/lib/RichText/Converter/Xslt/_fixtures/xhtml5/output/037-orderedListFormatted.xml, tests/lib/RichText/Validator/DocbookTest.php
| **JIRA issue**     | [IBX-3988](https://issues.ibexa.co/browse/IBX-3988)
| **Tests pass**     | yes/no
| **Doc needed**     | yes/no
This PR ensures that styling in lists are stored in docbook
Related DocBook Specs:
https://tdg.docbook.org/tdg/5.0/orderedlist.html
https://tdg.docbook.org/tdg/5.0/itemizedlist.html
**TODO**:
=> IBX-3988:  RichText formatting options not stored for Numbered List and Bulleted List

src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-editing.js
| **JIRA issue**     | [IBX-5054](https://issues.ibexa.co/browse/IBX-5054)
| **Tests pass**     | yes/no
Missing escaping of input
**TODO**:
=> IBX-5054: HTML code gets removed from the Custom tag's string attribute

src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-5147
**TODO**:
=> IBX-5147: [Rich text field type] Closing custom tag before finishing edition causes edition to hover.

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js, src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-editing.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-4927
**TODO**:
- [x Implement feature / fix a bug.
=> IBX-4927: Changing custom tag configuration breaks existing Rich Text fields that include this tag

src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js, src/bundle/Resources/public/js/CKEditor/link/link-command.js, src/bundle/Resources/public/js/CKEditor/link/link-editing.js, src/bundle/Resources/public/js/CKEditor/link/link-ui.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-2349 https://issues.ibexa.co/browse/IBX-5245 https://issues.ibexa.co/browse/IBX-5244
| **Bug**| yes
**TODO**:
=> IBX-2349/5244/5245: Added possibility to add link into embed image

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-5377
| **Bug**| yes
**TODO**:
=> IBX-5377: Added language of edited content to CKE configuration

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js, src/bundle/Resources/public/scss/_general.scss
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-5376
| **Doc needed**     | yes
For QA:
To test it you can change the language of the content in CKE
paste this code into line 84 in layout.html.twig in admin-ui
`window.ibexa.addConfig('richText.CKEditor.extraConfig', { language: { content: 'ar' }}, true);`
Doc:
In order to add or override config the custom config object should be added to the `window.ibexa.richText.CKEditor.extraConfig` key. The easiest way is to use `addConfig` method for example:
`window.ibexa.addConfig('richText.CKEditor.extraConfig', …
=> IBX-5376: Added possibility to change config of CKE

src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-editing.js, src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js, src/bundle/Resources/public/js/CKEditor/custom-tags/custom-tags.js, src/bundle/Resources/public/js/CKEditor/custom-tags/inline-custom-tag/inline-custom-tag-editing.js, src/bundle/Resources/public/js/CKEditor/custom-tags/inline-custom-tag/inline-custom-tag-ui.js, src/bundle/Resources/public/js/CKEditor/custom-tags/ui/custom-tag-attributes-view.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-5297
| **Target version** | l4.4
**For QA**
Inline custom tags should be tested as well.
This PR should fix https://issues.ibexa.co/browse/IBX-5257 as well.
**TODO**:
=> IBX-5297: Fixed custom tag without any attribute

src/bundle/Resources/public/js/CKEditor/custom-styles/inline/custom-style-inline-editing.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-4911
| **New feature**    | o
| **Target version** | v4.4
**Note for QA**
Strikethrough has the same problem, this PR solves problem in both.
**TODO**:
=> IBX-4911: Fixed breaking custom styles by italic or strikethrough

src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js
| **JIRA issue**     | [IBX-5788](https://issues.ibexa.co/browse/IBX-5788)
| **Bug**| yes
| **Target version** | `4.4`
`link` wasn't a proper DOM element in case of copying and pasting.
**TODO**:
=> IBX-5788: Fixed the `upcast` conversion in image editing

src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-command.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-editing.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-ui.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/helpers/config-helper.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/helpers/custom-attributes-config-helper.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-5757
| **Doc needed**     | yes
For doc:
In doc, we have a list of elements that can have custom attributes and classes: https://doc.ibexa.co/en/latest/content_management/rich_text/extend_online_editor/#configure-custom-data-attributes-and-classes
Now in the configuration we have two options, we can define `heading` and it will work like it was in the previous versions, the custom classes and attributes will be added to every heading. 
The second way is to specify custom attributes and classes to a specific heading: 'heading1', …
=> IBX-5757: Fixed custom classes and attributes on headings

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
| Question      | Answer
| ------------- | ---
| Tickets       | [IBX-5784](https://issues.ibexa.co/browse/IBX-5784)
| | [IBX-5743](https://issues.ibexa.co/browse/IBX-5743)
| | [IBX-4329](https://issues.ibexa.co/browse/IBX-4329)
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
CkEditor toolbar overflow fix
=> IBX-5784: CkEditor toolbar overflow fix

src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-command.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-5950
**TODO**:
=> IBX-5950: Fixed last value from one custom class appears in another

src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-command.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/ui/custom-attributes-form-view.js, src/bundle/Resources/public/scss/_balloon-form.scss
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-5981
**Requires:** https://github.com/ibexa/admin-ui/pull/828
**TODO**:
=> IBX-5981: Fixed handling multiple custom classes

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
| **JIRA issue**     | [IBX-5784](https://issues.ibexa.co/browse/IBX-5784)
| | [IBX-5743](https://issues.ibexa.co/browse/IBX-5743)
| **Bug/Improvement**| Bug
IBX-5784: CkEditor toolbar top position fixed
**TODO**:
=> IBX-5784, IBX-5743: CkEditor toolbar top position fixed

src/bundle/Resources/public/js/CKEditor/anchor/anchor-editing.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-6149
**TODO**:
=> IBX-6149: Richtext: Anchor is duplicated when entering newline

src/bundle/Resources/public/js/CKEditor/custom-attributes/ui/custom-attributes-form-view.js
| **JIRA issue**     | [IBX-6071](https://issues.ibexa.co/browse/IBX-6071)
| **Improvement**| yes
Basically, the title says it all.
**TODO**:
=> IBX-6071: Handled custom attributes deselection

phpstan-baseline.neon, src/bundle/Resources/public/scss/_balloon-form.scss
| **JIRA issue**     | [IBX-6121](https://issues.ibexa.co/browse/IBX-6121)
**TODO**:
=> IBX-6121: Added z-index to toolbar

src/bundle/Resources/public/js/CKEditor/custom-styles/inline/custom-style-inline-ui.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-6200
**TODO**:
=> IBX-6200: Changed the was custom styles list is diplayed

src/bundle/Resources/richtext/stylesheets/docbook/xhtml5/output/core.xsl, tests/lib/RichText/Converter/Xslt/_fixtures/docbook/014-link.xml, tests/lib/RichText/Converter/Xslt/_fixtures/xhtml5/edit/014-link.xml, tests/lib/RichText/Converter/Xslt/_fixtures/xhtml5/output/014-link.xml
| **JIRA issue**     | [IBX-5871](https://issues.ibexa.co/browse/IBX-5871)
**TODO**:
=> IBX-5871: Changed check if @xlink:title exists and not empty for a link element

phpstan-baseline.neon, src/bundle/Resources/config/fieldtype_services.yaml, src/lib/RichText/Renderer.php, tests/lib/RichText/RendererTest.php
| **JIRA issue**     | [IBX-6217](https://issues.ibexa.co/browse/IBX-6217)
| **Improvement**| yes
**TODO**:
=> IBX-6217: Forced `RichText\Renderer`to utilize `PermissionResolver` instead of `AuthorizationChecker`

src/bundle/Resources/public/scss/_balloon-form.scss
| **JIRA issue**     | [IBX-6354](https://issues.ibexa.co/browse/IBX-6354)
Added z-index for ck-balloon-panel_with-arrow because a problem with the toolbar for image variations was also detected
**TODO**:
=> IBX-6354: Set z-index for .ck-toolbar-container and .ck-balloon-panel_with-arrow

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-6313
**TODO**:
=> IBX-6313: Fixed anchor in empty paragraph

src/bundle/Resources/translations/ibexa_fieldtypes.en.xliff, src/bundle/Resources/views/RichText/content_fields.html.twig, src/lib/FieldType/RichText/Type.php
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-6415
| **Improvement**| no
| **Target version** | l4.6
**TODO**:
=> Renamed domain names

src/bundle/Resources/public/scss/_general.scss, src/bundle/Resources/public/scss/variables/colors.scss
| **JIRA issue**     | [IBX-6467](https://issues.ibexa.co/browse/IBX-6467)
| **Bug**| yes
Fixed styles for `is invalid` state and `focus` state
**Is invalid**
**Focus**
**TODO**:
=> IBX-6467: Richtext field validation is not styled properly

src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-command.js, src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-editing.js, src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-ui.js, src/bundle/Resources/public/js/CKEditor/embed/content/embed-command.js, src/bundle/Resources/public/js/CKEditor/embed/content/embed-editing.js, src/bundle/Resources/public/js/CKEditor/embed/content/embed-ui.js
| **JIRA issue**     | [IBX-6315](https://issues.ibexa.co/browse/IBX-6315)
| **Improvement**| yes
**TODO**:
=> IBX-6315: Edit/Preview embedded items

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js, src/bundle/Resources/public/scss/_balloon-form.scss, src/bundle/Resources/public/scss/_general.scss
| **JIRA issue**     | [IBX-6843](https://issues.ibexa.co/browse/IBX-6843)
| **Bug/Improvement**| Improvement
| **Doc needed**     | yes
=> IBX-6843: Focus mode

src/bundle/Resources/public/js/CKEditor/link/ui/link-form-view.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-7441
Note: the same issue was with the type number
**TODO**:
=> IBX-7441: Fixed custom attributes in link

src/bundle/Resources/public/scss/_general.scss
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-7468
**TODO**:
=> IBX-7468: Z-index issue with pop-ups in RTE fields

src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-editing.js, src/bundle/Resources/public/js/CKEditor/embed/content/embed-editing.js, src/bundle/Resources/public/scss/_general.scss
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-7747
**TODO**:
=> IBX-7747: Two or more embedded items makes popup menu unable to open

src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-command.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-editing.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-ui.js, src/bundle/Resources/public/js/CKEditor/plugins/elements-path.js, src/bundle/Resources/public/scss/_elements-path.scss, src/bundle/Resources/translations/ck_editor.en.xliff
| **JIRA issue**     | [IBX-6932](https://issues.ibexa.co/browse/IBX-6932)
**TODO**:
=> IBX-6932: Fixed adding custom attrs to list

src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-7740
**TODO**:
=> IBX-7740: Fixed links in embed image

src/bundle/Resources/public/js/CKEditor/anchor/anchor-editing.js, src/bundle/Resources/public/js/CKEditor/anchor/anchor-ui.js, src/bundle/Resources/public/scss/_general.scss
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-7762
**TODO**:
=> IBX-7762: Fixed anchor in list

.github/actions/composer-install/action.yaml, .github/workflows/ci.yaml, .github/workflows/frontend-ci.yaml, composer.json
| :ticket: Issue | IBX-8119 |
This PR bumps the minimum required version of PHP to 8.3.
`>=8.3` version constraint is set with expectation of compatibility with version PHP 9.
Additionally, this PR:
* enforces sorting of packages within `require` and `require-dev` sections of composer.json file
* replaces `~5.0.0@dev` declarations with their more development friendly `~5.0.x-dev`.
* adjusts github workflows to match new PHP version
* updates GH action versions
=> IBX-8119: Upgraded minimum PHP version to 8.3

src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js
=> IBX-8141: Added check if child is Element

phpstan-baseline.neon, tests/lib/Persistence/Legacy/Tests/Content/FieldValue/Converter/RichTextFieldValueConverterTest.php
=> IBX-8363: Corrected namespace for RichTextFieldValueConverterTest and added return types

src/bundle/Resources/public/js/CKEditor/link/ui/link-form-view.js
| :ticket: Issue | IBX-8340 |
It's not possible to create a link to a custom route. In the link modal:
- Entering "link" sends "http://link/" to the back-end
- Entering "/link" sends "[http:///link"](http://link/) to the back-end
New editor should behave in the same way as the old one (alloy) in 3.3:
- Entering "link" sends "http://link/" to the back-end
- Entering "/link" sends "[/link"](http://link/) to the back-end
Links will not be site-access aware ( so `/foobar ` won't be translated to `/admin/foobar` or `/pl/foobar`) but this was not the case in 3.3 either
=> IBX-8340: RichText: Not possible to create a link to a custom route

phpstan-baseline.neon, src/bundle/Resources/config/configuration.yaml, src/bundle/Resources/config/ui/mappers.yaml, src/contracts/Configuration/ProviderConfiguratorInterface.php, src/lib/Configuration/Provider/ConfigurableProvider.php, src/lib/Configuration/Provider/CustomTag.php, src/lib/Configuration/UI/Mapper/CustomTag.php, src/lib/Configuration/UI/Mapper/CustomTag/AttributeMapper.php, src/lib/Configuration/UI/Mapper/CustomTag/ChoiceAttributeMapper.php, tests/lib/Configuration/Provider/ConfigurableProviderTest.php
| :ticket: Issue | IBX-8434 |
This PR introduces `Ibexa\FieldTypeRichText\Configuration\Provider\ConfigurableProvider`, which decorates all available `Ibexa\Contracts\FieldTypeRichText\Configuration\Provider`s.
It's purpose is to allow modification of configuration (as a whole, not single items) before it is passed to frontend.
Alongside it, a `Ibexa\Contracts\FieldTypeRichText\Configuration\ProviderConfiguratorInterface` is introduced to allow injecting small services into the `ConfigurableProvider` that all take turns processing the configuration.
Four new tags are introduced as extension points for use:
* `ibexa.field_type.richtext.configuration.custom_style.configurator`
* `ibexa.field_type.richtext.configuration.custom_tag.configurator`
* …
=> IBX-8434: Added ProviderConfiguratorInterface to allow configuration post-processing

src/bundle/DependencyInjection/Configuration.php, tests/bundle/DependencyInjection/Configuration/ConfigurationTest.php, tests/bundle/DependencyInjection/Fixtures/custom_tags/output/000-attribute-type-number.yaml, tests/bundle/DependencyInjection/Fixtures/custom_tags/output/001-attribute-type-string.yaml, tests/bundle/DependencyInjection/Fixtures/custom_tags/output/002-attribute-type-boolean.yaml, tests/bundle/DependencyInjection/Fixtures/custom_tags/output/003-attribute-type-choice.yaml, tests/bundle/DependencyInjection/Fixtures/custom_tags/output/004-attribute-type-link.yaml
| **JIRA issue**     | [IBX-8150](https://issues.ibexa.co/browse/IBX-8150)
| **Doc needed**     | yes/no
Recipes level configuration:
https://github.com/ibexa/recipes-dev/pull/123/files
```
ibexa_fieldtype_richtext:
enabled_attribute_types:
- number
- string
- boolean
- link
```
To test this, feel free to remove one of the custom tag from allowed list - configuration should then fail same way as using not existing custom tag type.
**TODO**:
=> IBX-8150: Added option to enable attributes types

src/bundle/Resources/public/scss/_balloon-form.scss
| :ticket: Issue | IBX-8342 |
Fix issue IBX8342 issue on table in rich text
=> IBX-8342: Fixed creating tables in Online Editor

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
| :ticket: Issue | IBX-8502 |
Issue seems to come from the fact that `Intl` does not support 3 letter region subtags:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl
```
A locale identifier is a string that consists of:
```
PR adds a fallback to `eng-GB` for locales not supported by `Intl`.
=> IBX-8502: Added unsupported locale fallback

phpstan-baseline.neon
| :ticket: Issue | n/a |
Seems PHPStan now analyses sanity of code relying on `preg_match` `$matches` possible results.
After reviewing it a bit, I see that there's definitely a potential for improvements and there might be even some bugs.
However doing it now to fix CI is too risky and requires QA. Therefore, after talking to @Steveb-p, I created IBX-8919 for further consideration. 
PHPStan failures:
```
------ ------------------------------------------------------------------------------------------------------- 
Line   src/lib/FieldType/RichText/RichTextStorage.php                                                         
------ ------------------------------------------------------------------------------------------------------- 
78     Offset 2 does not …
```
=> [PHPStan] Aligned baseline after PHPStan update

src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js, src/bundle/Resources/public/js/CKEditor/custom-tags/helpers/panel-helper.js, src/bundle/Resources/public/js/CKEditor/custom-tags/inline-custom-tag/inline-custom-tag-ui.js, src/bundle/Resources/public/js/CKEditor/custom-tags/ui/custom-tag-attributes-view.js, src/bundle/Resources/public/js/CKEditor/custom-tags/ui/custom-tag-form-view.js, src/bundle/Resources/public/scss/_balloon-form.scss, src/bundle/Resources/public/scss/_custom-tag-attributes.scss
=> IBX-8824: The popup for custom tags with multiple fields is not scrollable

src/bundle/Resources/public/js/CKEditor/block-alignment/block-alignment-editing.js, src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js, src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-editing.js, src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-settings-command.js, src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-settings-ui.js, src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-toolbar.js, src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js, src/bundle/Resources/public/js/CKEditor/custom-tags/custom-tags.js, src/bundle/Resources/public/scss/_custom-tag.scss, src/bundle/Resources/translations/ck_editor.en.xliff
| :ticket: Issue | IBX-8845 |
This PR adds possibility to align custom tags.
=> IBX-8845: Added alignments for custom tags

phpstan-baseline.neon, src/lib/FieldType/RichText/RichTextStorage.php, tests/lib/FieldType/RichText/RichTextStorageTest.php
| :ticket: Issue | IBX-8534 |
- https://github.com/ibexa/core/pull/435
=> IBX-8534: Dropped deprecated context and getIndexData from Storage

src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js
| :ticket: Issue | [IBX-8850](https://issues.ibexa.co/browse/IBX-8850) |
=> IBX-8850: Focus bug in rich text editor

src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-ui.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/ui/custom-attributes-form-view.js, src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js, src/bundle/Resources/public/js/CKEditor/custom-tags/ui/custom-tag-attributes-view.js, src/bundle/Resources/public/js/CKEditor/custom-tags/ui/custom-tag-form-view.js, src/bundle/Resources/public/js/CKEditor/helpers/custom-panel-helper.js, src/bundle/Resources/public/scss/_balloon-form.scss, src/bundle/Resources/public/scss/_custom-panel.scss, src/bundle/Resources/public/scss/ckeditor.scss
| :ticket: Issue | IBX-9154 |
It was necessary to add a scroll for the custom tags and custom attributes panels. PR also solves
https://issues.ibexa.co/browse/IBX-9233
=> IBX-9154: The dropdown for custom class is illegible

src/bundle/Resources/public/js/CKEditor/custom-tags/inline-custom-tag/inline-custom-tag-editing.js
| :ticket: Issue | [IBX-9243](https://issues.ibexa.co/browse/IBX-9243) |
=> IBX-9243: linebreaks in Inline custom tags markup (eztemplateinline) breakes the editor

src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-command.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/helpers/config-helper.js, src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js
| :ticket: Issue | [IBX-9296](https://issues.ibexa.co/browse/IBX-9296) |
Custom class was there under `custom-classes` attribute, but it was in form of `ibexa-embed-type-image {custom_class}` so `cleanClasses` method was removing this whole attribute (as `ibexa-embed-type-image` wasn't in custom classes options config and all custom-classes had to be matched)
I've added to config info about this component class and before any checks I remove it from attribute.
Also, I have to remove it later manually from model attributes, as otherwise `ibexa-embed-type-image` is duplicated - probably comes from container declaration and from custom-classes, co one of these origins had to be cleared.
=> IBX-9296: Custom CSS classes not working for "embedimage"

src/bundle/Resources/public/js/CKEditor/custom-attributes/ui/custom-attributes-form-view.js, src/bundle/Resources/public/js/CKEditor/link/link-command.js, src/bundle/Resources/public/js/CKEditor/link/link-ui.js, src/bundle/Resources/public/js/CKEditor/link/ui/link-form-view.js, src/bundle/Resources/public/scss/_balloon-form.scss, src/bundle/Resources/translations/ck_editor.en.xliff
| :ticket: Issue | [IBX-9297](https://issues.ibexa.co/browse/IBX-9297) |
=> IBX-9297: Custom CSS can not be removed from link element

src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js
| :ticket: Issue | [IBX-9326](https://issues.ibexa.co/browse/IBX-9326) |
=> IBX-9326: The image link with a class is producing an error

src/bundle/Resources/public/scss/_balloon-form.scss
| :ticket: Issue | IBX-9392 |
- https://github.com/ibexa/fieldtype-richtext/pull/124
Toolbar appears below title/locaton header:
After fix:
Fix does not seem to break IBX-6354:
- See ticket for how to reproduce.. Should do regression test and see that IBX-6354 doesn't break
=> IBX-9392: Richtext editor menu is hidden below "ibexa-edit-header"

src/bundle/Resources/views/RichText/embed/content.html.twig, src/bundle/Resources/views/RichText/embed/content_inline.html.twig, src/bundle/Resources/views/RichText/embed/location.html.twig, src/bundle/Resources/views/RichText/embed/location_inline.html.twig
| :ticket: Issue | IBX-9513 |
- https://github.com/ibexa/fieldtype-query/pull/35
- https://github.com/ibexa/core/pull/474
- https://github.com/ibexa/http-cache/pull/56
Fixed obsolete `ibexa_content:` single colon controller references.
In theory should be visible when trying to embed content inside a RichText field.
=> IBX-9513: Fixed obsolete `ibexa_content` Controller references

src/bundle/Resources/public/js/CKEditor/common/chips-button-view/chips-button-view.js, src/bundle/Resources/public/js/CKEditor/common/multivalue-dropdown/utils.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-ui.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/ui/custom-attributes-form-view.js, src/bundle/Resources/public/js/CKEditor/link/ui/link-form-view.js, src/bundle/Resources/public/scss/_balloon-form.scss, src/bundle/Resources/public/scss/_custom-panel.scss
| :ticket: Issue | [IBX-9298](https://issues.ibexa.co/browse/IBX-9298) |
=> IBX-9298: multiple Custom CSS - no visual indication of selected items

src/bundle/Resources/config/translation.yaml, src/lib/Translation/Extractor/OnlineEditorCustomAttributesExtractor.php
| :ticket: Issue | [IBX-9509](https://issues.ibexa.co/browse/IBX-9509) |
When doing merge up there will be need for extra work, as this class was removed in 5.0 https://github.com/ibexa/fieldtype-richtext/pull/185
=> IBX-9509: Revert deprecation of custom attributes labels extractor

.github/workflows/ci.yaml, composer.json, phpstan-baseline.neon, rector.php, src/bundle/Command/MigrateRichTextNamespacesCommand.php, src/bundle/Templating/Twig/Extension/RichTextConverterExtension.php, src/bundle/Templating/Twig/Extension/YoutubeIdExtractorExtension.php, src/lib/Form/Type/RichTextFieldType.php
| :ticket: Issue | IBX-9584 |
Enabled and executed automatic refactoring rules defined for Symfony 6.x.
* [Form] Added missing return type declarations
* [CLI] Replaced deprecated Command::{$defaultName, $defaultDescription} with the AsCommand attribute
* [PHP] Updated method reference syntax
Additionally added rector job to CI setup to prevent merging up code which is not compatible with Symfony 6+. 
Sanities.
N/A
=> IBX-9584: Resolved Symfony 6.x deprecations

src/bundle/Resources/public/js/CKEditor/link/link-ui.js
| :ticket: Issue | [IBX-8849](https://issues.ibexa.co/browse/IBX-8849) |
Bug occurs when we pass undefined value, therefore this change sets value to null either if link doesn't exist or getAttribute returns undefined
=> IBX-8849: Texts "Title" and "Undefined" in Landing page Block rich text link are bad aligned

src/bundle/Resources/views/RichText/style/default.html.twig, src/bundle/Resources/views/RichText/style/default_inline.html.twig
| :ticket: Issue | N/A       |
> The spaceless filter is deprecated as of Twig 3.12 and will be removed in Twig 4.0.
See https://twig.symfony.com/doc/3.x/deprecated.html 
Limitations and field types rendering.
N/A
=> [Twig] Removed usage of deprecated spaceless filter

ignore-gte-php8.1-errors.neon, phpstan-baseline.neon, phpstan.neon
| :ticket: Issue | IBX-XXXXX |
This is a library, so regardless of declared types in phpdoc, we sometimes need to run checks for user-supplied data.
=> Set `treatPhpDocTypesAsCertain` to `false` for PHPStan

src/bundle/Resources/public/js/CKEditor/link/link-ui.js
| :ticket: Issue | [IBX-9738](https://issues.ibexa.co/browse/IBX-9738) |
=> IBX-9738: Link URL and title is removed when selecting full link text (pt 2)

composer.json, phpstan-baseline.neon, phpstan.neon, src/bundle/IbexaFieldTypeRichTextBundle.php, src/lib/FieldType/RichText/RichTextStorage.php, src/lib/FieldType/RichText/RichTextStorage/Gateway.php, src/lib/FieldType/RichText/RichTextStorage/Gateway/DoctrineStorage.php, src/lib/Form/DataTransformer/RichTextValueTransformer.php, src/lib/Persistence/Legacy/MigrateRichTextNamespaces/Gateway/DoctrineDatabase.php, tests/integration/Repository/RichTextFieldTypeIntegrationTest.php, tests/integration/Repository/SetupFactory/LegacySetupFactory.php
> [!CAUTION]
> # Merge together with other IBX-8471 Pull Requests
> - [x] Make sure TMP commit(s) are dropped before merging
| :ticket: Issue | IBX-8471 |
Upgrading Symfony dependencies to version 7 along with necessary 3rd party packages and codebase changes.
Key changes:
Sanity tests and/or regression builds.
=> IBX-8471: Upgraded codebase to Symfony 7

rector.php, src/bundle/Resources/config/configuration.yaml, src/bundle/Resources/config/fieldtype_services.yaml, src/bundle/Resources/config/settings/fieldtype_services.yaml
| :ticket: Issue | IBX-9968  |
Enabled Rector Symfony 7.0, 7.1 and 7.2 sets. Resolved the following deprecations:
```
* [symfony/dependency-injection] Replaced deprecated !tagged YAML tag to !tagged_iterator 
```
Sanities.
=> IBX-9968: Resolved Symfony 7.x deprecations

.github/workflows/browser-tests.yaml, src/bundle/Resources/public/scss/variables/colors.scss, src/bundle/Resources/public/scss/variables/vars.scss
| :ticket: Issue | IBX-10078 |
=> IBX-10078: Fixed shape of richtext field

src/lib/FieldType/RichText/RichTextStorage/Gateway/DoctrineStorage.php, src/lib/Persistence/Legacy/MigrateRichTextNamespaces/Gateway/DoctrineDatabase.php, tests/integration/Repository/RichTextFieldTypeIntegrationTest.php, tests/lib/FieldType/RichText/Gateway/_fixtures/contentobjects.php
=> IBX-9941: Fixed schema tables names

phpstan-baseline.neon, tests/lib/RichText/Converter/LinkTest.php
| :ticket: Issue | IBX-9727 |
- https://github.com/ibexa/core/pull/590
We were trying to incorrectly instantiate an `UnauthorizedException` (just for the purpose of mocking) and since ibexa/core#590 we can't get away with it.
Visible when running unit tests:
```
1) Error
The data provider specified for Ibexa\Tests\FieldTypeRichText\RichText\Converter\LinkTest::testConvertBadLocationLink is invalid.
TypeError: Ibexa\Core\Base\Exceptions\UnauthorizedException::__construct(): Argument #2 ($function) must be of type string, int given, called in /home/andrew/Product/packages/ibexa/fieldtype-richtext/tests/lib/RichText/Converter/LinkTest.php on line 278
/home/andrew/Product/packages/ibexa/fieldtype-richtext/vendor/ibexa/core/src/lib/Base/Exceptions/UnauthorizedExce …
```
=> IBX-9727: [Tests] Fixed strict types after ibexa/core#590 changes

src/bundle/Resources/public/scss/_general.scss
| :ticket: Issue | IBX-10087 |
=> IBX-10087: Left-aligned image overlaps with blocks in Richtext field

package.json, src/bundle/Resources/encore/ibexa.webpack.custom.config.js, src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js
| :ticket: Issue | IBX-10173 |
That's why I vouched for not using path.resolve in requires - changes from root dir broke this bundle...
Also, most of these changes are only because of linter/prettier
=> IBX-10173: Extract webpack files from root dir

src/lib/RichText/Validator/CustomTemplateValidator.php, tests/lib/RichText/Validator/CustomTemplateValidatorTest.php
| :ticket: Issue | IBX-10262 |
Updated the `CustomTemplateValidator` to utilize readonly properties and refined validation error handling to improve code consistency and reliability.
=> Updated `CustomTemplateValidator` for readonly properties
