ibexa/fieldtype-richtext

src/bundle/Resources/views/RichText/content_fields.html.twig, src/bundle/Resources/views/RichText/embed/content.html.twig, src/bundle/Resources/views/RichText/embed/content_denied.html.twig, src/bundle/Resources/views/RichText/embed/content_inline.html.twig, src/bundle/Resources/views/RichText/embed/content_inline_denied.html.twig, src/bundle/Resources/views/RichText/embed/location.html.twig, src/bundle/Resources/views/RichText/embed/location_denied.html.twig, src/bundle/Resources/views/RichText/embed/location_inline.html.twig, src/bundle/Resources/views/RichText/embed/location_inline_denied.html.twig, src/bundle/Resources/views/themes/standard/ezrichtext/custom_tags/ezyoutube.html.twig, src/bundle/Templating/Twig/Extension/RichTextConfigurationExtension.php, src/bundle/Templating/Twig/Extension/RichTextConverterExtension.php, src/bundle/Templating/Twig/Extension/YoutubeIdExtractorExtension.php, tests/bundle/Templating/Twig/Extension/YoutubeIdExtractorExtensionTest.php
https://issues.ibexa.co/browse/IBX-1543
=> IBX-1543: Replaced deprecated twig functions

tests/integration/Repository/RichTextFieldTypeIntegrationTest.php
| **JIRA issue**     | [IBX-1549](https://issues.ibexa.co/browse/IBX-1549)
| **Target version** | 2,3
cross merge of https://github.com/ezsystems/ezplatform-richtext/pull/218
**TODO**:
=> IBX-1549: Cross fixed test after changes in kernel

src/bundle/DependencyInjection/Compiler/RichTextHtml5ConverterPass.php, src/bundle/Resources/config/fieldtype_services.yaml, src/bundle/Resources/config/form.yaml, src/bundle/Resources/config/rest.yaml, src/bundle/Resources/config/settings/fieldtype_services.yaml, src/bundle/Resources/config/settings/fieldtypes.yaml, src/bundle/Resources/config/settings/storage_engines/legacy/external_storage_gateways.yaml, src/bundle/Resources/config/templating.yaml, src/bundle/Resources/views/RichText/embed/content.html.twig, src/bundle/Resources/views/RichText/embed/content_inline.html.twig, src/bundle/Resources/views/RichText/embed/location.html.twig, src/bundle/Resources/views/RichText/embed/location_inline.html.twig, tests/bundle/DependencyInjection/Compiler/RichTextHtml5ConverterPassTest.php, tests/integration/Repository/SetupFactory/CoreSetupFactoryTrait.php
=> IBX-1853: Rebranded services names

src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js, src/bundle/Resources/public/js/CKEditor/services/content-service.js
=> IBX-2007: Rebranded REST media types in ibexa/fieldtype-richtext repository

src/bundle/Resources/public/scss/_general.scss
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-1841
**TODO**:
=> IBX-1841: Added missing frame in richtext

src/bundle/Resources/public/scss/_general.scss
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-1390
**TODO**:
=> IBX-1390: Fixed anchor icon placement

src/bundle/Resources/public/js/CKEditor/services/content-service.js
=> IBX-2061: Rebranded REST route prefix in ibexa/fieldtype-richtext repository

src/bundle/Resources/config/prepend/ezrichtext.yaml
=> IBX-1210: Rebranded @ezdesign ibexa/fieldtype-richtext repository

tests/lib/Configuration/UI/Config/Mapper/CustomTagTest.php
=> IBX-1853: Used rebranded namespaces and services names

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js, src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js, src/bundle/Resources/public/js/CKEditor/move/move-command.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-2132
**TODO**:
=> IBX-2132: Fixed moving custom tags, embed, image

src/bundle/DependencyInjection/IbexaFieldTypeRichTextExtension.php, src/bundle/Resources/config/configuration.yaml, src/bundle/Resources/config/default_settings.yaml, src/bundle/Resources/config/fieldtype_services.yaml, src/bundle/Resources/config/settings/fieldtype_services.yaml, src/bundle/Resources/config/translation.yaml, src/bundle/Resources/config/ui/mappers.yaml, src/lib/RichText/Validator/CustomTagsValidator.php, tests/bundle/DependencyInjection/IbexaFieldTypeRichTextExtensionTest.php, tests/integration/Repository/SetupFactory/CoreSetupFactoryTrait.php, tests/lib/RichText/Validator/CustomTagsValidatorTest.php, tests/lib/_settings/common.yaml
| **JIRA issue**                          | [IBX-1696](https://issues.ibexa.co/browse/IBX-1696)
| **Type**                                   | feature
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#31
Rebranded service container parameter names and Ibexa Config Resolver namespaces to follow unified pattern
=> IBX-1696: Rebranded Container parameters and Config Resolver namespaces

src/bundle/Templating/Twig/Extension/RichTextConfigurationExtension.php, src/contracts/Configuration/ProviderService.php, src/lib/Configuration/AggregateProvider.php, src/lib/FieldType/RichText/Type.php, src/lib/RichText/RelationProcessor.php, tests/bundle/Templating/Twig/Extension/YoutubeIdExtractorExtensionTest.php, tests/integration/Repository/RichTextFieldTypeIntegrationTest.php, tests/lib/Configuration/AggregateProviderTest.php, tests/lib/Configuration/Provider/AlloyEditorTest.php, tests/lib/Configuration/Provider/BaseCustomTemplateProviderTestCase.php, tests/lib/Configuration/Provider/BaseProviderTestCase.php, tests/lib/Configuration/Provider/CKEditorTest.php, tests/lib/Configuration/UI/Config/Mapper/CustomTagTest.php, tests/lib/FieldType/RichText/SearchFieldTest.php, tests/lib/FieldType/RichTextTest.php, tests/lib/Form/DataTransformer/RichTextTransformerTest.php, tests/lib/Persistence/Legacy/Tests/Content/FieldValue/Converter/RichTextFieldValueConverterTest.php, tests/lib/RichText/DOMDocumentFactoryTest.php, tests/lib/RichText/InputHandlerTest.php, tests/lib/RichText/RelationProcessorTest.php, tests/lib/RichText/Validator/CustomTagsValidatorTest.php, tests/lib/RichText/Validator/ValidatorAggregateTest.php
=> IBX-1853: Used rebranded namespaces in comments

tests/integration/Repository/RichTextFieldTypeIntegrationTest.php
=> IBX-1853: Used rebranded namespaces in code

src/bundle/Resources/public/js/CKEditor/block-alignment/block-alignment-command.js, src/bundle/Resources/public/js/CKEditor/block-alignment/block-alignment-editing.js, src/bundle/Resources/public/js/CKEditor/block-alignment/block-alignment-ui.js, src/bundle/Resources/public/js/CKEditor/block-alignment/block-alignment.js, src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js, src/bundle/Resources/public/scss/_general.scss, src/bundle/Resources/translations/ck_editor.en.xliff
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-2345
**TODO**:
=> IBX-2345: Added alignments to images

src/bundle/Resources/encore/ez.webpack.custom.config.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-2413
**TODO**:
=> IBX-2413: Changed relative paths to encore aliases

src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-ui.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-2474
**TODO**:
=> IBX-2474: Fixed error when only custom classes are set

src/bundle/Resources/public/js/CKEditor/embed/content/embed-editing.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-2813
**TODO**:
=> IBX-2813: Fixed error when entering richtext with embed

src/bundle/Resources/config/prepend/ezpublish.yaml, src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js, src/bundle/Resources/public/js/CKEditor/upload-image/upload-image-command.js, src/bundle/Resources/public/js/CKEditor/upload-image/upload-image-editing.js, src/bundle/Resources/public/js/CKEditor/upload-image/upload-image-ui.js, src/bundle/Resources/public/js/CKEditor/upload-image/upload-image.js, src/bundle/Resources/translations/ck_editor.en.xliff
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-2898
**TODO**:
=> IBX-2898: Introduced easy way of adding images to CKEditor

src/bundle/Resources/public/js/CKEditor/custom-attributes/ui/custom-attributes-form-view.js, src/bundle/Resources/public/js/CKEditor/custom-tags/ui/custom-tag-form-view.js
| **JIRA issue**     | [IBX-2867](https://issues.ibexa.co/browse/IBX-2867)
| **Bug**| yes
| **Target version** | 4,0
Check if customAttributes exist and are an array before trying to iterate.
**TODO**:
=> IBX-2867: Fixed custom tags when defined without attributes

src/bundle/Resources/encore/ez.webpack.custom.config.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-2982
**TODO**:
=> IBX-2982: Fixed encore config for version 34.1.0

.github/workflows/frontend-ci.yaml
JIRA ref: https://issues.ibexa.co/browse/IBX-3919
=> IBX-3919: Frontend CI doesn't run when there are no changes in frontend files

src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-command.js
| **JIRA issue**     | https://issues.ibexa.co/browse/EZP-30765
| **Target version** | `4.2`
**TODO**:
=> EZP-30765: Fixed removing custom attributes when switching element

src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-command.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-3307
| **Target version** | 4.2
**TODO**:
=> IBX-3307: Fixed custom attributes on embeds

src/bundle/Resources/public/js/CKEditor/link/link-ui.js, src/bundle/Resources/public/js/CKEditor/link/ui/link-form-view.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-4122
| **Target version** | 4.2
**TODO**:
=> IBX-4122: Fixed canceling UDW in link settings

src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-ui.js, src/bundle/Resources/translations/ck_editor.en.xliff
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-3667
| **Target version** | 4.2
**Requires:**
https://github.com/ibexa/admin-ui/pull/627
https://github.com/ibexa/icons/pull/21
**TODO**:
=> IBX-3667: Update icon for embed inline

src/bundle/DependencyInjection/IbexaFieldTypeRichTextExtension.php
| **JIRA issue**     | N/A
| **Target version** | `main`
**TODO**:
=> Changed name of configuration for translation extraction

src/bundle/Resources/public/scss/_custom-tag-attributes.scss
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-5051
=> IBX-5051: Unable to edit custom tags with long values in page builder

src/bundle/Resources/public/scss/_general.scss
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-4988
**TODO**:
=> IBX-4988: Toolbar popups are obscured by the header

src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-4989
**TODO**:
=> IBX-4989: Rich Text custom tag attributes preview doesn't update properly

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-5325
**TODO**:
=> IBX-5325: Fixed error on enter to edit mode

src/bundle/Resources/public/scss/_general.scss, src/bundle/Resources/public/scss/variables/vars.scss
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-4908
**TODO**:
=> IBX-4908: Fixed styling for custom styles in editor

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
Reverts ibexa/fieldtype-richtext#86
=> Revert "IBX-5784: CkEditor toolbar overflow fix"

src/bundle/Resources/public/js/CKEditor/link/link-ui.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-5870
| **Target version** | l4.5
**TODO**:
=> IBX-5870: Fixed link editing

src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js, src/bundle/Resources/public/js/CKEditor/custom-tags/ui/custom-tag-attributes-view.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-5741
| **Target version** | v4.5
**TODO**:
=> IBX-5741: Fixed collapsing Custom Tag attribute preview

src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-6025
**TODO**:
=> IBX-6025: Properties of one custom tag showing in the preview of another

src/bundle/Resources/public/js/CKEditor/anchor/anchor-ui.js, src/bundle/Resources/public/js/CKEditor/anchor/ui/anchor-form-view.js, src/bundle/Resources/translations/ck_editor.en.xliff
| **JIRA issue**     | [IBX-5715](https://issues.ibexa.co/browse/IBX-5715)
I had no other idea to verify if an element is unique, the previous solution doesn't work anymore. I'd love to hear other ideas for checking the uniqueness of the ID
**TODO**:
=> IBX-5715: Added validate if anchor value is unique and valid

src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-6026
**TODO**:
=> IBX-6026: Fixed deleting multiple custom tags in once

src/bundle/Resources/public/js/CKEditor/anchor/anchor-ui.js
| **JIRA issue**     | [IBX-6148](https://issues.ibexa.co/browse/IBX-6148) and [IBX-6151](https://issues.ibexa.co/browse/IBX-6151) 
**TODO**:
=> IBX-6151, IBX-6148: Added check if balloon hasView to prevent trying it add again it, corrected logic for countElementsWithSameId

src/bundle/Resources/public/js/CKEditor/link/link-ui.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-6162
**TODO**:
=> IBX-6162: Add link params to all selected paragraphs

src/bundle/Resources/public/scss/_general.scss
| **JIRA issue**     | [IBX-5932](https://issues.ibexa.co/browse/IBX-5932)
**TODO**:
=> IBX-5932: Added max-height for .ck.ck-dropdown__panel

src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-ui.js, src/bundle/Resources/public/js/CKEditor/custom-attributes/ui/custom-attributes-form-view.js, src/bundle/Resources/public/scss/_balloon-form.scss
| **JIRA issue**     | [IBX-6078](https://issues.ibexa.co/browse/IBX-6078)
| **Target version** |`v4.5` 
Adding a new button with the inscription on it was agreed and approved by the Design team
**TODO**:
=> IBX-6078: Added Revert to saved button

src/bundle/Resources/public/js/CKEditor/upload-image/upload-image-editing.js
| **JIRA issue**     | [IBX-6352](https://issues.ibexa.co/browse/IBX-6352)
| **Bug**| yes
| **New feature**    |no
As the title states.
**TODO**:
=> IBX-6352: Blocked image upload when moving it inside RTE

src/bundle/Resources/public/js/CKEditor/embed/image/embed-image-editing.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-6400
| **Bug/Improvement**| bg
**TODO**:
=> IBX-6400: Moving images between lines can result in a disapperance of another image

src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-editing.js, src/bundle/Resources/public/js/CKEditor/link/link-command.js, src/bundle/Resources/public/js/CKEditor/link/link-editing.js, src/bundle/Resources/public/js/CKEditor/link/link-ui.js, src/bundle/Resources/public/js/CKEditor/link/ui/link-form-view.js, src/bundle/Resources/public/scss/_balloon-form.scss
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-6889
**TODO**:
=> IBX-6889: Added custom attributes to links

src/bundle/Resources/public/scss/_tools.scss
=> Upgraded CKE to latest version

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-7195
| **Bug/Improvement**| bug
**TODO**:
=> IBX-7195: [Focus mode] Rich text options do not display correctly

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js, src/bundle/Resources/public/scss/_balloon-form.scss, src/bundle/Resources/public/scss/_general.scss
| **JIRA issue**     | [IBX-7329](https://issues.ibexa.co/browse/IBX-7329)
**TODO**:
=> IBX-7329: Enhancing UX: Name Updates for Product 4.6 LTS+

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
| **JIRA issue**     | N/A
| **Doc needed**     | yes
**TODO**:
=> Added event to manipulate CKEditor config before initialization 

src/bundle/Resources/public/scss/_general.scss
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-6380
**TODO**:
=> IBX-6380: Fixed position of anchor in lists

.github/workflows/frontend-ci.yaml, package.json, src/bundle/Resources/public/scss/_balloon-form.scss
JIRA ref: https://issues.ibexa.co/browse/IBX-7928
=> IBX-7928: As a developer, I want to have newest patch version of eslint config installed

src/bundle/Resources/public/js/CKEditor/link/link-editing.js
| **JIRA issue**     | https://issues.ibexa.co/browse/IBX-7930
**TODO**:
=> IBX-7930: Fixed link position in paragraph

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
| :ticket: Issue | IBX-8352|
In case distraction-free mode is not enabled there shouldn't be any JS exception present.
=> IBX-8352: Handled disabled distraction-free mode

src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-command.js
… 
| :ticket: Issue | [IBX-8337](https://issues.ibexa.co/browse/IBX-8337) |
=> IBX-8337: Can't add Custom classes and attributes for TR element with multiple line

src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js
| :ticket: Issue | [IBX-7694](https://issues.ibexa.co/browse/IBX-7694) |
=> IBX-7694: Richtext custom tag attributes don't have effect on existing tags

src/bundle/DependencyInjection/Configuration.php, src/bundle/DependencyInjection/IbexaFieldTypeRichTextExtension.php, src/bundle/IbexaFieldTypeRichTextBundle.php, src/lib/FieldType/RichText/Value.php, src/lib/Form/Type/RichTextFieldType.php
| :ticket: Issue | IBX-8138 |
Applied rules from Symfony 5 Rector set lists.
No QA needed. Regression tests should be enough.
This is code refactoring without behavior change. No documentation changes needed.
=> IBX-8138: [Rector] Applied rules from Symfony 5 Rector set lists

src/bundle/Resources/encore/ez.webpack.custom.config.js, src/bundle/Resources/public/js/CKEditor/common/input-number/input-number-view.js, src/bundle/Resources/public/js/CKEditor/custom-tags/block-custom-tag/custom-tag-ui.js, src/bundle/Resources/public/js/CKEditor/custom-tags/ui/custom-tag-attributes-view.js, src/bundle/Resources/public/js/CKEditor/custom-tags/ui/custom-tag-form-view.js
=> IBX-8150: Added option to enable attributes types

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
| :ticket: Issue | [IBX-9097](https://issues.ibexa.co/browse/IBX-9097) |
=> IBX-9097: [PB] Error with Richtext validator in nested_attribute

src/bundle/Templating/Twig/Extension/RichTextConfigurationExtension.php
| :ticket: Issue | IBX-XXXXX |
Removing ez_richtext_config deprecation
=>  Removing ez_richtext_config deprecation

src/bundle/Resources/public/js/CKEditor/custom-attributes/custom-attributes-ui.js
=> IBX-9583: Fixed closing custom attributes when clicking outside

src/bundle/Resources/public/scss/_balloon-form.scss
=> IBX-9677: Fixed zindex in embed image

src/bundle/Resources/public/scss/_balloon-form.scss
=> IBX-8852: added gap between label and switch button

phpstan-baseline.neon, src/bundle/Resources/public/scss/_general.scss
=> IBX-8822: Fixed arrow colors

.github/workflows/frontend-ci.yaml, phpstan-baseline.neon, src/bundle/Resources/public/scss/variables/colors.scss, src/bundle/Resources/public/scss/variables/vars.scss
| :ticket: Issue | IBX-9926 |
- https://github.com/ibexa/share/pull/58
- https://github.com/ibexa/fieldtype-richtext-rte/pull/13
- https://github.com/ibexa/admin-ui/pull/1531
=> IBX-9926: [Collaboration] Users list for CKEditor

composer.json, tests/integration/IbexaTestKernel.php
| :ticket: Issue | IBX-XXXXX |
Added ibexa/twig-components to require-dev
=> Added ibexa/twig-components to require-dev

src/bundle/Resources/public/js/CKEditor/custom-tags/inline-custom-tag/inline-custom-tag-editing.js
| :ticket: Issue | IBX-10268 |
=> IBX-10268: Fixed custom tag upcast

tests/lib/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/008-anchor.docbook.xml, tests/lib/RichText/Converter/Xslt/_fixtures/xhtml5/edit/lossy/010-duplicatedIds.docbook.xml
It seems our library for XML received updates which affected the way nodes' ids are generated.
=> [Tests] Fixed xml nodes' ids after Libxml update

src/bundle/Resources/public/scss/_general.scss
| :ticket: Issue | IBX-10068 |
=> IBX-10068: Unified list style for nested lists

src/bundle/Resources/public/js/CKEditor/embed/content-inline/embed-inline-editing.js, src/bundle/Resources/public/js/CKEditor/embed/content/embed-editing.js
| :ticket: Issue | IBX-10440 |
- https://github.com/ibexa/dashboard/pull/161
- https://github.com/ibexa/admin-ui/pull/1687
- https://github.com/ibexa/discounts/pull/289
- https://github.com/ibexa/form-builder/pull/198
- https://github.com/ibexa/product-catalog-date-time-attribute/pull/42
- https://github.com/ibexa/scheduler/pull/150
- https://github.com/ibexa/fieldtype-matrix/pull/78
- https://github.com/ibexa/workflow/pull/158
- https://github.com/ibexa/page-builder/pull/457
- https://github.com/ibexa/product-catalog/pull/1382
- https://github.com/ibexa/taxonomy/pull/375
- https://github.com/ibexa/corporate-account/pull/325
- https://github.com/ibexa/tree-builder/pull/188
- https://github.com/ibexa/tree-builder/pull/188
- …
=> IBX-10440: Changed base icon size

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js, src/bundle/Resources/public/scss/_general.scss, src/bundle/Resources/public/scss/variables/vars.scss
| :ticket: Issue | IBX-10402 |
=> IBX-10402: Missing hover state on richtext field

src/bundle/Resources/public/js/CKEditor/core/base-ckeditor.js
| :ticket: Issue | IBX-10661 |
=> IBX-10661: Fixed selector on focus
